FROM ubuntu:18.04

copy mlops /mlops/

copy requirements.txt /mlops/

RUN mkdir /mlops/models

WORKDIR /mlops

RUN apt-get update && apt-get install -y --no-install-recommends python3 python3-pip && apt-get clean

RUN pip3 install --no-cache-dir -r requirements.txt

CMD ["python3", "hand-written-digits.py"]